# -*- coding: utf-8 -*-
"""collatz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19C6yKFOuNtahgA7_joMB5isoIbV54ktb
"""

for i in range(1,1001):
    n=i
    c=0
    while n!=1:
        n=n//2 if n%2==0 else n*3+1
        c+=1
    print(c)